<?php return   [
  [
    'name' => 'Atalanta Bergamasca Calcio',
    'short_name' => 'Atalanta',
    'city' => 'Bergamo',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/8/81/Logo_Atalanta_Bergamo.svg/210px-Logo_Atalanta_Bergamo.svg.png',
    'description' => "<p>L'Atalanta Bergamasca Calcio, meglio nota come Atalanta, è una società calcistica italiana con sede nella città di Bergamo.</p><p>Fondata il 17 ottobre 1907, viene soprannominata \"regina delle provinciali\" poiché, avendo preso parte a 61 edizioni della Serie A a girone unico, è la squadra col maggior numero di presenze nel massimo campionato italiano di calcio sia tra quelle che non rappresentano capoluoghi di regione sia tra quelle che non hanno mai vinto lo scudetto. Il club detiene il record assoluto di promozioni nella massima serie ed è, al pari del Genoa, quello che ha vinto più volte un campionato cadetto.</p>",
    'points' => 41,
    'goal_difference' => 14,
  ],
  [
    'name' => 'Bologna Football Club 1909',
    'short_name' => 'Bologna',
    'city' => 'Bologna',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/9/97/Logo_Bologna_FC_2018.svg/140px-Logo_Bologna_FC_2018.svg.png',
    'description' => "Il Bologna Football Club 1909 (AFI: /boˈloɲɲa 'futbol ˈklɛb/), meglio noto come Bologna (o colloquialmente con la sigla BFC, «Bologna Football Club»), è una società calcistica italiana per azioni con sede nell'omonima città emiliana. Milita in Serie A, il massimo livello della piramide calcistica nazionale.",
    'points' => 35,
    'goal_difference' => -2,
  ],
  [
    'name' => 'Unione Sportiva Cremonese',
    'short_name' => 'Cremonese',
    'city' => 'Cremona',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/0/09/Uscremonesestemma.png/210px-Uscremonesestemma.png',
    'description' => "<p>L'Unione Sportiva Cremonese, meglio conosciuta come Cremonese, è una società calcistica italiana con sede nella città di Cremona. Milita in Serie A, la massima divisione del campionato italiano di calcio.</p>",
    'points' => 9,
    'goal_difference' => -25,
  ],
  [
    'name' => 'Empoli Football Club',
    'short_name' => 'Empoli',
    'city' => 'Empoli',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/e/e4/Empoli_logo_2021.svg/140px-Empoli_logo_2021.svg.png',
    'description' => "<p>L'Empoli Football Club, meglio noto come Empoli, è una società calcistica italiana con sede nella città di Empoli, nella città metropolitana di Firenze. Milita in Serie A, la massima divisione del campionato italiano.</p>",
    'points' => 28,
    'goal_difference' => -9,
  ],

  [
    'name' => 'ACF Fiorentina',
    'short_name' => 'Fiorentina',
    'city' => 'Firenze',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/ACF_Fiorentina.svg/140px-ACF_Fiorentina.svg.png',
    'description' => "<p>L'ACF Fiorentina, meglio nota come Fiorentina, è una società calcistica italiana con sede nella città di Firenze. Milita in Serie A, la massima divisione del campionato italiano.<p></p>Fondata il 29 agosto 1926 dal marchese Luigi Ridolfi Vay da Verrazzano come Associazione Calcio Firenze, l'anno seguente la società muta denominazione temporaneamente in Associazione Fiorentina del Calcio e poi stabilmente in Associazione Calcio Fiorentina, quest'ultima mantenuta fino alla rifondazione della stagione 2002-2003, giocata sotto il nome di Florentia Viola prima di adottare l'attuale denominazione. Dal 2019 il club è di proprietà dell'imprenditore italo-statunitense Rocco Commisso.</p>",
    'points' => 25,
    'goal_difference' => -6,
  ],

  [
    'name' => 'Hellas Verona Football Club',
    'short_name' => 'Hellas Verona',
    'city' => 'Verona',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/0/06/Genoacfcstemma.svg/140px-Genoacfcstemma.svg.png',
    'description' => "<p>L'Hellas Verona Football Club, meglio noto come Hellas Verona o più semplicemente Verona, è una società calcistica italiana con sede nella città di Verona, militante nel campionato di Serie A.</p><p> Fondata nel 1903 con il nome di Associazione Calcio Hellas,dall'istituzione della Serie A a girone unico (1929) è stata l'unica squadra di una città non capoluogo di regione a vincere, nella stagione 1984-1985, il campionato di massima serie. Proprio gli anni 1980 sono stati il periodo di maggiori soddisfazioni sportive per il club, che arrivò anche due volte consecutive (delle tre complessive) in finale di Coppa Italia, disputando inoltre diverse partite nelle coppe europee (con una partecipazione alla Coppa dei Campioni e due alla Coppa UEFA). I gialloblù hanno partecipato a 31 campionati di Serie A, 53 di Serie B e 6 di Serie C/Serie C1; la compagine scaligera è inoltre la seconda (alle spalle del Brescia) per presenze nel campionato cadetto, torneo che ha vinto in tre occasioni. Occupa il tredicesimo posto nella graduatoria della tradizione sportiva italiana secondo i criteri della FIGC.</p>",
    'points' => 17,
    'goal_difference' => -14,
  ],
  [
    'name' => 'Football Club Inter Milan',
    'short_name' => 'Inter',
    'city' => 'Milano',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/140px-FC_Internazionale_Milano_2021.svg.png',
    'description' => "<p>Il Football Club Internazionale Milano, meglio conosciuto come Internazionale o più semplicemente come Inter, è una società calcistica italiana con sede nella città di Milano.</p><p>Fondato il 9 marzo 1908 da un gruppo di soci dissidenti del Milan, il club ha sempre militato nella massima serie del campionato nazionale a partire dalla propria prima partita ufficiale, nel 1909, ed è l'unico ad aver partecipato a tutte le edizioni della Serie A, istituita nella stagione 1929-30. Fin dalla fondazione, indossa una divisa a strisce verticali nerazzurre, a parte una breve parentesi nel 1928 quando adottò una maglia bianca rossocrociata.</p>",
    'points' => 47,
    'goal_difference' => 16
  ],
  [
    'name' => 'Juventus Football Club',
    'short_name' => 'Juventus',
    'city' => 'Torino',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Juventus_FC_2017_icon_%28black%29.svg/140px-Juventus_FC_2017_icon_%28black%29.svg.png',
    'description' => "<p>La Juventus Football Club (dal latino: iuventūs, «gioventù»), meglio nota come Juventus (/juˈvɛntus/), è una società calcistica italiana con sede nella città di Torino.</p><p>Fondata nel 1897 da un gruppo di studenti liceali locali,[2] la Juve, com'è colloquialmente abbreviata, è il secondo club calcistico professionistico per anzianità tra quelli tuttora attivi nel Paese, dopo il Genoa (1893); è il più titolato e con maggior tradizione sportiva oltreché uno dei più blasonati al mondo con 70 trofei ufficiali vinti durante la militanza al vertice della piramide sportiva nazionale, tra cui il primato di 36 titoli di campione d'Italia e 11 in competizioni UEFA. Partecipa alla Serie A, il massimo campionato italiano, a cui ha preso parte stabilmente sin dall'esordio nel 1900, eccezione fatta per la stagione 2006-2007. Dopo aver esordito in divisa rosanero, ai primi del Novecento adottò l'odierna tenuta di gioco bianconera.</p>",
    'points' => 32,
    'goal_difference' => 19,
  ],
  [
    'name' => 'Società Sportiva Lazio',
    'short_name' => 'Lazio',
    'city' => 'Roma',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/6/62/Stemma_della_Societ%C3%A0_Sportiva_Lazio.svg/140px-Stemma_della_Societ%C3%A0_Sportiva_Lazio.svg.png',
    'description' => "<p>La Società Sportiva Lazio, meglio nota come S.S. Lazio o più semplicemente Lazio, è una società polisportiva italiana di Roma, nota soprattutto per la sua sezione calcistica.</p><p>Fu fondata il 9 gennaio 1900 come Società Podistica Lazio da quindici atleti guidati dal sottufficiale dei Bersaglieri Luigi Bigiarelli.[2][3] Dopo aver esordito in divisa bianca, ai primi del Novecento adottò l'odierna tenuta di gioco biancoceleste.[4] La Lazio è presente dal 6 maggio 1998 alla Borsa di Milano nell'indice FTSE Italia Small Cap:[5] è stata la prima società calcistica italiana a quotarsi in Borsa dove sono state successivamente ammesse anche la sua concittadina Roma e la Juventus.</p>",
    'points' => 42,
    'goal_difference' => 20,
  ],
  [
    'name' => 'Unione Sportiva Lecce',
    'short_name' => 'Lecce',
    'city' => 'Lecce',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/c/c7/US_Lecce.svg/210px-US_Lecce.svg.png',
    'description' => "<p>L'Unione Sportiva Lecce, nota semplicemente come Lecce, è una società calcistica italiana con sede nella città di Lecce. Milita in Serie A, la massima divisione del campionato italiano.</p>",
    'points' => 27,
    'goal_difference' => -3,
  ],
  [
    'name' => 'Associazione Calcio Milan',
    'short_name' => 'Milan',
    'city' => 'Milano',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/140px-Logo_of_AC_Milan.svg.png',
    'description' => "<p>L'Associazione Calcio Milan, meglio nota come A.C. Milan o anche Milan (AFI: /ˈmilan/), è una società calcistica italiana fondata nel 1899 con sede nella città di Milano.</p><p>La squadra milita nella Serie A del campionato italiano di calcio dalla sua introduzione nella stagione 1929-1930, dove ha giocato pressoché stabilmente: da lì, infatti, ha partecipato a 88 campionati di Serie A a girone unico su 90, e a due campionati di Serie B nelle stagioni 1980-1981 e 1982-1983. L'esordio in massima serie nel periodo antecedente il girone unico risale al 1900.</p>",
    'points' => 47,
    'goal_difference' => 11,
  ],
  [
    'name' => 'Associazione Calcio Monza',
    'short_name' => 'Monza',
    'city' => 'Monza',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/6/65/Associazione_Calcio_Monza_%282019%29.svg/210px-Associazione_Calcio_Monza_%282019%29.svg.png',
    'description' => "<p>L'Associazione Calcio Monza, meglio nota come AC Monza o semplicemente Monza, è una società calcistica italiana con sede nella città di Monza. Milita in Serie A, la massima divisione del campionato italiano di calcio.</p>",
    'points' => 29,
    'goal_difference' => -6,
  ],
  [
    'name' => 'Società Sportiva Calcio Napoli',
    'short_name' => 'Napoli',
    'city' => 'Napoli',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/e/ed/SSC_Napoli_2007.svg/140px-SSC_Napoli_2007.svg.png',
    'description' => "<p>La Società Sportiva Calcio Napoli, meglio nota come Napoli, è una società calcistica italiana con sede nella città di Napoli. Milita in Serie A, la massima serie del campionato italiano.</p><p>Fondata nel 1926[1] con il nome di Associazione Calcio Napoli, assunse poi la denominazione di SSC Napoli nel 1964. In seguito al fallimento della società nel 2004, il presidente Aurelio De Laurentiis fonda la Napoli Soccer che ne rileva il titolo sportivo e viene iscritta alla Serie C1, per poi ritornare alla denominazione precedente con la promozione in Serie B nel 2006.</p>",
    'points' => 65,
    'goal_difference' => 43,
  ],
  [
    'name' => 'Associazione Sportiva Roma',
    'short_name' => 'Roma',
    'city' => 'Roma',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/0/0e/AS_Roma_Logo_2017.svg/140px-AS_Roma_Logo_2017.svg.png',
    'description' => "<p>L'Associazione Sportiva Roma (AFI: /assoʧaʦˈʦjone sporˈtiva ˈroma/), meglio nota come AS Roma o più semplicemente Roma, è una società calcistica italiana con sede nella città di Roma. Milita in Serie A, la massima divisione del campionato italiano.</p><p>Fondata nel 1927 grazie alla fusione di tre squadre, ha come colori sociali il rosso e il giallo, tonalità cromatiche corrispondenti al gonfalone del Campidoglio. Dal 23 maggio 2000 è quotata alla Borsa Italiana, nel cui listino fa parte dell'indice FTSE Italia Small Cap: la Lupa, uno dei soprannomi che contraddistinguono la Roma insieme a Giallorossi, Magica e Capitolini, è infatti una dei tre club di calcio italiani (insieme a Lazio e Juventus) a essere presente nella borsa valori italiana.</p>",
    'points' => 44,
    'goal_difference' => 11,
  ],
  [
    'name' => 'Unione Sportiva Salernitana 1919',
    'short_name' => 'Salernitana',
    'city' => 'Salerno',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/6/6a/US_Salernitana_1919.svg/140px-US_Salernitana_1919.svg.png',
    'description' => "<p>L'Unione Sportiva Salernitana 1919, meglio nota come Salernitana, è una società calcistica italiana con sede nella città di Salerno. Milita in Serie A, il primo livello della piramide calcistica italiana.</p><p>Fondata la società originale il 19 giugno 1919 da una cordata capeggiata da Matteo Schiavone, nel corso della sua storia è stata rifondata per tre volte: nel 1927 in seguito alla costituzione di un nuovo sodalizio con l'attuale identità granata, nel 2005 e nel 2011 per motivi finanziari. L'attuale società fu, infatti, fondata come Salerno Calcio nel 2011 (aderendo all'art. 52.10 del regolamento federale), e riprese i segni distintivi della Salernitana a partire dal 2012. Il 19 giugno 2019 la squadra campana ha compiuto 100 anni di storia calcistica.</p>",
    'points' => 24,
    'goal_difference' => -16,
  ],
  [
    'name' => 'Unione Calcio Sampdoria',
    'short_name' => 'Sampdoria',
    'city' => 'Genoa',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/5/50/Sampdoriastemma.svg/140px-Sampdoriastemma.svg.png',
    'description' => "<p>L'Unione Calcio Sampdoria, meglio nota come Sampdoria, è una società calcistica italiana con sede nella città di Genova.</p><p>Soprannominata la Samp[3] o il Doria, è nata il 12 agosto 1946 dalla fusione tra la Sampierdarenese (nata come polisportiva nel 1891, e come sezione calcio nel 1899) e l'Andrea Doria (sorta come polisportiva nel 1895, e come sezione calcio nel 1900). Milita nella Serie A del campionato italiano di calcio. Decima fra i club con la migliore tradizione sportiva in Italia, fa inoltre parte dell'European Club Association.</p>",
    'points' => 11,
    'goal_difference' => -27,
  ],
  [
    'name' => 'Unione Sportiva Sassuolo Calcio',
    'short_name' => 'Sassuolo',
    'city' => 'Sassuolo',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/a/a4/Ussassuolostemma.svg/140px-Ussassuolostemma.svg.png',
    'description' => "<p>L'Unione Sportiva Sassuolo Calcio, meglio nota come Sassuolo, è una società calcistica italiana con sede nella città di Sassuolo, in provincia di Modena.</p><p>Costituita nel 1920, dalla stagione sportiva 2013-2014 milita in Serie A. I suoi colori sociali sono il nero e il verde, da cui il soprannome di neroverdi; altro soprannome noto del club è Sasôl (\"Sassuolo\" in dialetto modenese). Dopo aver usufruito per decenni dello stadio Enzo Ricci di Sassuolo, e aver poi brevemente giocato sul manto dello stadio Alberto Braglia di Modena, dal 2013 i neroverdi disputano le loro partite casalinghe al Mapei Stadium di Reggio Emilia.</p>",
    'points' => 27,
    'goal_difference' => -8,
  ],
  [
    'name' => 'Spezia Calcio',
    'short_name' => 'Spezia',
    'city' => 'La Spezia',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Spezia_Calcio.svg/140px-Spezia_Calcio.svg.png',
    'description' => "<p>Lo Spezia Calcio, comunemente noto come Spezia, è una società calcistica italiana con sede nella città della Spezia. Milita nel campionato di Serie A.</p><p>Fondata nel 2008 come Associazione Sportiva Dilettantistica Spezia Calcio 2008, porta avanti la tradizione sportiva iniziata nel 1906 oon la costituzione della sezione calcistica dello Sport Club Spezia, cui sono seguite varie rifondazioni e riorganizzazioni, con denominazioni quali Foot Ball Club Spezia, Associazione Calcio Spezia e Spezia Calcio 1906, fallito al termine del campionato di Serie B 2007-08, conclusosi con la retrocessione in Serie C1.</p>",
    'points' => 20,
    'goal_difference' => -20,
  ],
  [
    'name' => 'Torino Football Club',
    'short_name' => 'Torino',
    'city' => 'Torino',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/0/04/Torino_FC_logo.svg/140px-Torino_FC_logo.svg.png',
    'description' => "<p>Il Torino Football Club, meglio conosciuto come Torino, è una società calcistica italiana con sede nella città di Torino. Il club odierno, rifondato nel 2005, è la continuazione dello storico sodalizio sorto nel 1906 dalla fusione tra il Torinese e i soci dissidenti del Foot-Ball Club Juventus, denominato Foot Ball Club Torino sino al 1936, Associazione Calcio Torino fino al 1943, dal 1945 al 1958 e ancora dal 1959 al 1977, Torino FIAT nel 1944, Associazione Calcio Talmone Torino nel 1958-59 e Torino Calcio dal 1977 al 2005. Milita nel campionato di Serie A.</p>",
    'points' => 31,
    'goal_difference' => -1,
  ],
  [
    'name' => 'Udinese Calcio',
    'short_name' => 'Udinese',
    'city' => 'Udine',
    'serie' => 'A',
    'logo' => 'https://upload.wikimedia.org/wikipedia/it/thumb/a/ae/Logo_Udinese_Calcio_2010.svg/140px-Logo_Udinese_Calcio_2010.svg.png',
    'description' => "<p>L'Udinese Calcio, meglio nota come Udinese, è una società calcistica italiana con sede nella città di Udine. Si tratta di uno dei club più antichi d'Italia, essendo nato nel 1896, anche se la sua sezione calcistica risale ufficialmente al 1911.</p><p>I suoi colori sociali sono il bianco e il nero, ripresi dallo stemma comunale della città; in ragione di tale accostamento cromatico, i giocatori guadagnarono il soprannome di bianconeri e di zebrette.</p>",
    'points' => 31,
    'goal_difference' => 3,
  ]
];
